### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by successed** [FrankHeijden/Insights#7]
error :+1: 

`[14:09:45 WARN]: [Insights] Task #336 for Insights v2.7.6 generated an exception
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_222]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_222]
        at net.frankheijden.insights.tasks.BossBarTask.run(BossBarTask.java:16) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-175]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-175]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

`

Version 1.14.4 paper

plugin version : v2.7.6

**Comment by FrankHeijden** [comment]
Hi, when does this error occur? Which command did you execute?

**Comment by FrankHeijden** [comment]
Hi please try the latest build from here: https://ci.frankheijden.net/job/Insights/20/artifact/target/Insights.jar
